/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness. The process is up (no dependencies checked) */
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness. The process is up and the database answers */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Who is signed in, and which side of the app to show them (D-024)
         * @description Creates the person's record on their first request.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/side": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save the onboarding answer, customer or salon. Final once chosen (D-030); the same answer again is accepted */
        put: operations["updateMySide"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Save the signed-in person's own name and optional email (BE-018, DF-18)
         * @description The name is trimmed and must be 2–60 characters. The email is optional: empty or missing clears it; otherwise it is
         *     trimmed, stored in lower case, at most 254 characters and must look like an email address.
         */
        put: operations["updateMyProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in admin. An INVITED admin becomes ACTIVE on their first request with MFA done (BE-020) */
        get: operations["getAdminMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/admins/invites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Invite another admin by email (BE-020, D-013). Audit-logged
         * @description The email is trimmed and lower-cased. Supabase creates the login and sends its invite email; if the email already
         *     has a Supabase login, none is sent and that login is used. The new admin is INVITED until their first login with
         *     the authenticator app.
         */
        post: operations["inviteAdmin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/salon/salons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create the signed-in person's salon; they become its owner (BE-017, D-033, D-035)
         * @description Only for a person who chose the salon side (D-030) and belongs to no salon yet. The salon starts as DRAFT.
         *     Text fields are trimmed. The phone defaults to the owner's login number (D-046).
         */
        post: operations["createSalon"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/salon/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The signed-in person's one salon and their role in it (BE-017, D-036) */
        get: operations["getMySalon"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/salon/salon": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * The owner edits the salon's profile while it isn't live (BE-017, D-039)
         * @description Same body and rules as creating it. Allowed while DRAFT, UNDER_VERIFICATION or REJECTED.
         */
        put: operations["updateMySalon"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @enum {string} */
        HealthStatus: "UP" | "DOWN";
        HealthResponse: {
            status: components["schemas"]["HealthStatus"];
            /** @description Backend build version */
            version: string;
            database?: components["schemas"]["HealthStatus"];
        };
        /**
         * @description Which interface the app shows (D-024)
         * @enum {string}
         */
        UserSide: "CUSTOMER" | "SALON";
        SalonProfileRequest: {
            /** @description 1–30 characters after trimming (D-046) */
            name: string;
            /**
             * @description The number customers call: an Indian number of 10 digits, with or without +91, 91 or a leading 0; spaces and
             *     dashes are fine. Missing or empty: the owner's login number (D-046, DF-32)
             */
            phone?: string;
            address: components["schemas"]["SalonAddress"];
            type: components["schemas"]["SalonType"];
        };
        SalonAddress: {
            /** @description House, shop or building, and street */
            line1: string;
            /** @description Area or locality */
            area: string;
            /** @description Optional */
            landmark?: string;
            city: string;
            state: components["schemas"]["IndianState"];
            pincode: string;
        };
        SalonResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @description E.164 without +, e.g. 919876543210 */
            phone: string;
            address: components["schemas"]["SalonAddress"];
            type: components["schemas"]["SalonType"];
            status: components["schemas"]["SalonStatus"];
            /** @description Why our team rejected it; only when REJECTED */
            rejectionReason?: string;
        };
        MySalonResponse: {
            salon: components["schemas"]["SalonResponse"];
            role: components["schemas"]["SalonRole"];
        };
        /** @enum {string} */
        SalonType: "MEN" | "WOMEN" | "UNISEX";
        /**
         * @description Onboarding state (D-033); only LIVE salons add staff, show up for customers and take bookings
         * @enum {string}
         */
        SalonStatus: "DRAFT" | "UNDER_VERIFICATION" | "LIVE" | "REJECTED" | "SUSPENDED";
        /**
         * @description The person's role in their one salon (D-039)
         * @enum {string}
         */
        SalonRole: "OWNER" | "STAFF";
        /**
         * @description India's 28 states and 8 union territories (DF-32)
         * @enum {string}
         */
        IndianState: "ANDHRA_PRADESH" | "ARUNACHAL_PRADESH" | "ASSAM" | "BIHAR" | "CHHATTISGARH" | "GOA" | "GUJARAT" | "HARYANA" | "HIMACHAL_PRADESH" | "JHARKHAND" | "KARNATAKA" | "KERALA" | "MADHYA_PRADESH" | "MAHARASHTRA" | "MANIPUR" | "MEGHALAYA" | "MIZORAM" | "NAGALAND" | "ODISHA" | "PUNJAB" | "RAJASTHAN" | "SIKKIM" | "TAMIL_NADU" | "TELANGANA" | "TRIPURA" | "UTTAR_PRADESH" | "UTTARAKHAND" | "WEST_BENGAL" | "ANDAMAN_AND_NICOBAR_ISLANDS" | "CHANDIGARH" | "DADRA_AND_NAGAR_HAVELI_AND_DAMAN_AND_DIU" | "DELHI" | "JAMMU_AND_KASHMIR" | "LADAKH" | "LAKSHADWEEP" | "PUDUCHERRY";
        MeResponse: {
            /**
             * Format: uuid
             * @description Supabase user id
             */
            id: string;
            /** @description Phone number used to sign in, as Supabase returns it (e.g. 919000000001) */
            phone?: string;
            side?: components["schemas"]["UserSide"];
            /** @description The person's name; missing until given at onboarding */
            name?: string;
            /** @description Optional email, in lower case */
            email?: string;
        };
        UpdateProfileRequest: {
            /** @description 2–60 characters after trimming */
            name: string;
            /** @description Optional; empty or missing clears it */
            email?: string | null;
        };
        UpdateSideRequest: {
            side: components["schemas"]["UserSide"];
        };
        /**
         * @description INVITED until the admin's first login with the authenticator app, then ACTIVE
         * @enum {string}
         */
        AdminStatus: "INVITED" | "ACTIVE";
        AdminResponse: {
            /**
             * Format: uuid
             * @description Supabase user id of the admin's login
             */
            id: string;
            /** @description Login email, in lower case */
            email: string;
            status: components["schemas"]["AdminStatus"];
        };
        InviteAdminRequest: {
            /** @description Trimmed and lower-cased; at most 254 characters and shaped like an email address */
            email: string;
        };
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        ErrorBody: {
            /**
             * @description Stable machine-readable code. Shared codes: BAD_REQUEST, UNAUTHORIZED, FORBIDDEN, NOT_FOUND,
             *     METHOD_NOT_ALLOWED, PAYLOAD_TOO_LARGE, UNSUPPORTED_MEDIA_TYPE, RATE_LIMITED, INTERNAL.
             *     Features add their own.
             */
            code: string;
            /** @description Human-readable; may change; never contains stack traces or secrets */
            message: string;
            /** @description Same as the X-Request-Id response header */
            requestId?: string;
        };
    };
    responses: {
        /** @description Missing, expired or invalid login token. The app should send the person to sign in again */
        Unauthorized: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "UNAUTHORIZED",
                 *         "message": "Please sign in again.",
                 *         "requestId": "3f0c9a52-7d1e-4b8a-9a0e-2c1d5b6e7f80"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /**
         * @description Signed in, but not allowed: NOT_ADMIN (this login is not one of our admins) or MFA_REQUIRED (an admin whose login
         *     hasn't passed the authenticator-app step)
         */
        AdminForbidden: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "MFA_REQUIRED",
                 *         "message": "Log in with the code from your authenticator app to continue.",
                 *         "requestId": "3f0c9a52-7d1e-4b8a-9a0e-2c1d5b6e7f80"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Any error. See `ErrorBody.code` for the reason */
        Error: {
            headers: {
                "X-Request-Id": components["headers"]["XRequestId"];
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": {
                 *         "code": "NOT_FOUND",
                 *         "message": "No such endpoint.",
                 *         "requestId": "3f0c9a52-7d1e-4b8a-9a0e-2c1d5b6e7f80"
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description Request ID (echoed from the request if safe, otherwise generated) */
        XRequestId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The backend process is running */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "UP",
                     *       "version": "0.1.0"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend and database are up */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "UP",
                     *       "version": "0.1.0",
                     *       "database": "UP"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description The database is not answering; stop routing traffic here */
            503: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "status": "DOWN",
                     *       "version": "0.1.0",
                     *       "database": "DOWN"
                     *     }
                     */
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in person */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "3f0c9a52-7d1e-4b8a-9a0e-2c1d5b6e7f80",
                     *       "phone": "919000000001"
                     *     }
                     */
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["Error"];
        };
    };
    updateMySide: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "side": "CUSTOMER"
                 *     }
                 */
                "application/json": components["schemas"]["UpdateSideRequest"];
            };
        };
        responses: {
            /** @description Saved; returns the updated person */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            400: components["responses"]["Error"];
            401: components["responses"]["Unauthorized"];
            /** @description A different side was already chosen; it can't be changed (error code SIDE_ALREADY_CHOSEN) */
            409: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "Priya Sharma",
                 *       "email": "priya@example.com"
                 *     }
                 */
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Saved; returns the updated person */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Malformed body, or a field fails validation (error codes INVALID_NAME, INVALID_EMAIL) */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            default: components["responses"]["Error"];
        };
    };
    getAdminMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The signed-in admin */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "3f0c9a52-7d1e-4b8a-9a0e-2c1d5b6e7f80",
                     *       "email": "admin@glide.test",
                     *       "status": "ACTIVE"
                     *     }
                     */
                    "application/json": components["schemas"]["AdminResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["AdminForbidden"];
            default: components["responses"]["Error"];
        };
    };
    inviteAdmin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "email": "new.admin@example.com"
                 *     }
                 */
                "application/json": components["schemas"]["InviteAdminRequest"];
            };
        };
        responses: {
            /** @description Invited; returns the pending admin */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "id": "3f0c9a52-7d1e-4b8a-9a0e-2c1d5b6e7f80",
                     *       "email": "new.admin@example.com",
                     *       "status": "INVITED"
                     *     }
                     */
                    "application/json": components["schemas"]["AdminResponse"];
                };
            };
            /** @description Malformed body, or the email fails validation (error code INVALID_EMAIL) */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["AdminForbidden"];
            /** @description This email is already an admin (error code ADMIN_ALREADY_EXISTS) */
            409: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Supabase refused or failed to send the invite; nothing was saved (error code INVITE_FAILED) */
            502: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The server has no Supabase secret key, so it can't invite (error code INVITES_UNAVAILABLE) */
            503: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createSalon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "Glow Studio",
                 *       "address": {
                 *         "line1": "12, MG Road",
                 *         "area": "Indiranagar",
                 *         "landmark": "Near the metro",
                 *         "city": "Bengaluru",
                 *         "state": "KARNATAKA",
                 *         "pincode": "560038"
                 *       },
                 *       "type": "UNISEX"
                 *     }
                 */
                "application/json": components["schemas"]["SalonProfileRequest"];
            };
        };
        responses: {
            /** @description Created; returns the salon (DRAFT) and the role OWNER */
            201: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MySalonResponse"];
                };
            };
            /** @description Malformed body, or a field fails validation (error codes INVALID_SALON_NAME, INVALID_SALON_PHONE, INVALID_ADDRESS) */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description The person hasn't chosen the salon side (error code NOT_SALON_SIDE) */
            403: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The person already belongs to a salon (error code ALREADY_IN_SALON) */
            409: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    getMySalon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The salon and the person's role */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MySalonResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description The person belongs to no salon yet (error code NO_SALON) */
            404: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    updateMySalon: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "name": "Glow Studio",
                 *       "address": {
                 *         "line1": "12, MG Road",
                 *         "area": "Indiranagar",
                 *         "landmark": "Near the metro",
                 *         "city": "Bengaluru",
                 *         "state": "KARNATAKA",
                 *         "pincode": "560038"
                 *       },
                 *       "type": "UNISEX"
                 *     }
                 */
                "application/json": components["schemas"]["SalonProfileRequest"];
            };
        };
        responses: {
            /** @description Saved; returns the salon and the role OWNER */
            200: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MySalonResponse"];
                };
            };
            /** @description Malformed body, or a field fails validation (error codes INVALID_SALON_NAME, INVALID_SALON_PHONE, INVALID_ADDRESS) */
            400: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
            /** @description The person is staff, not the owner (error code NOT_OWNER) */
            403: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The person belongs to no salon yet (error code NO_SALON) */
            404: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The salon is LIVE or SUSPENDED (error code SALON_NOT_EDITABLE) */
            409: {
                headers: {
                    "X-Request-Id": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
